name: Auto-assignment
# Auto assignment of reviewers based on the proposal

on:
  issues:
    types:
        - opened
        - edited
jobs:
    assign_reviewers:
        runs-on: ubuntu-latest

        steps:
          - name: Check out code
            uses: actions/checkout@v3
            
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '18.x' 
            
          - name: Install dependencies
            run: |
              npm install
              npm install @octokit/rest

          - name: Check if issue has [Proposal] label
            id: check_proposal_label
            run: |
              echo "has_proposal_label=${{ contains(github.event.issue.title, 'proposal') }}" >> "$GITHUB_OUTPUT"
              category3=$(echo "${{ github.event.issue.body }}" | grep -e "Category" -A2 | grep -v "Category" | grep "\S")
              echo "category=$category3" >> "$GITHUB_OUTPUT"
            shell: bash
            
          - name: Run auto-assignment script
            if: ${{steps.check_proposal_label.outputs.has_proposal_label == 'true'}}
            run: node .github/workflows/assign_reviewers.js ${{ github.repository }} ${{ github.event.issue.number }} "${{ steps.check_proposal_label.outputs.category }}"
            env:
              TOKEN: ${{ secrets.GITHUB_TOKEN }}

            